config/routes.rb
Rails.application.routes.draw do
  root "static_pages#home"
  get "/signup", to: "users#new"
  get "/help", to: "static_pages#help"
  get "/about", to: "static_pages#about"
  get "/contact", to: "static_pages#contact"
  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:index, :create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t "form_contain" %> <%= pluralize object.errors.count, t("error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if feed_items.any? %>
  <ol class="microposts">
    <%= render feed_items, user: current_user %>
  </ol>
  <%= will_paginate feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for micropost do |form| %>
  <%= render "shared/error_messages", object: form.object %>
  <div class="field">
    <%= form.text_area :content, placeholder: t("post.compose") %>
  </div>
  <%= form.submit t("post.post"), class: "btn btn-primary" %>
  <span class="picture">
    <%= form.file_field :picture, accept: "image/jpeg,image/gif,image/png" %>
  </span>
<% end %>

app/views/shared/_stats.html.erb
<% user ||= current_user %>
<div class="stats">
  <%=link_to relationships_path id: user.id, type: "following" do %>
    <strong id="following" class="stat">
      <%= user.following.count %>
    </strong>
    <%= t "follow.following" %>
  <% end %>
  <%= link_to relationships_path id: user.id, type: "followers" do %>
    <strong id="followers" class="stat">
      <%= user.followers.count %>
    </strong>
    <%= t "follow.followers" %>
  <% end %>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to t("post.view"), current_user %></span>
<span><%= pluralize current_user.microposts.count, t("post.micropost") %></span>